### ISSUE TITLE
Value Error during PCA

### ISSUE THREAD

**Issue by jcha9928** [ME-ICA/me-ica#3]
Hi,

I got the following error below:

```
-Computing PCA of optimally combined multi-echo data
0
33.7092933106 168546.466553
Out shape is  (53, 64, 52, 275)
Traceback (most recent call last):
  File "/Users/posnerlab/Documents/github/me-ica/meica.libs/tedana.py", line 1012, in <module>
    nc,dd = tedpca(options.ste)
  File "/Users/posnerlab/Documents/github/me-ica/meica.libs/tedana.py", line 561, in tedpca
    none,ctb,betasv,v_T = fitmodels_direct(catd,v.T,eimum,t2s,tes,mmixN=vTmixN,full_sel=False)
  File "/Users/posnerlab/Documents/github/me-ica/meica.libs/select_model_fft20e.py", line 41, in fitmodels_direct
    if mmixN == None: mmixN=mmix
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by prantikk** [comment]
This is an unusual problem.  Could you send me a sample dataset?

**Comment by jcha9928** [comment]
Here is the dropbox link for the data.

 

https://www.dropbox.com/sh/dw7g1iucal2ntb3/AABjxHhoLHe34e_Y-yB15Ewga?dl=0

 

 

 

-- 

 

Sincerely,

Jiook

**Comment by emdupre** [comment]
Hi, 

This is actually an error I've seen several times before. I've updated the master copy here to patch these problem (commits b2781dd087ab9de99a2ec3925f04f02ce84f0adc and da6ac4c23a59145530a16bd6f25c676460fe9436). Could you please `git pull` to access the latest version and let me know if you're still experiencing errors?

**Comment by jcha9928** [comment]
problem solved!! Thanks so much!!
