### ISSUE TITLE
godec.py update

### ISSUE THREAD

**Issue by dowdlelt** [ME-ICA/me-ica#4]
Good afternoon folks,
In reference to the recently published [Power et al MEICA + GODEC](http://www.pnas.org/content/early/2018/02/07/1720985115) denoising paper, is there an updated version of godec.py available?
Thus far I have only been able to find the [bitbucket 0.1 version](https://bitbucket.org/prantikk/me-ica/src/e21c93a6358ec43eb4c915f2ae42711014e6f3d3/meica.libs/godec.py?at=v3&fileviewer=file-view-default) which has incomplete help text and returns an indexing error when ran. This error appears to stem from the transition from multiple echoes to the optimal combination. 

Is there a newer version or a flag that I have missed in the code to use it? 

Thank you all for the work on MEICA

**Comment by dowdlelt** [comment]
Specific Error after running:
python ~/soft/code/python/prantikk_meica/meica.libs/godec.py -d ./zcat_ffd.nii.gz --TEs=15,36,58 -r 1

`-- GoDec fMRI Denoising 0.1--
++ Loading Data
mkdir: cannot create directory ‘GD’: File exists
-Computing PCA of spatially concatenated multi-echo data
0
29.8893448438 149446.724219
1
22.2734561719 111367.280859
2
16.996989375 84984.946875
++Starting Go Decomposition
Finished at iteration 100
Traceback (most recent call last):
  File "/home/dowdlelt/soft/code/python/prantikk_meica/meica.libs/godec.py", line 647, in <module>
    dogs(ranks,drank=drank,inpower=inpower,norm_mode=options.norm_mode)
  File "/home/dowdlelt/soft/code/python/prantikk_meica/meica.libs/godec.py", line 574, in dogs
    artout = unmask(gdout[0],eimum)
  File "/home/dowdlelt/soft/code/python/prantikk_meica/meica.libs/godec.py", line 144, in unmask
    out[M,:] = np.reshape(data,(Nm,nt))
  File "/home/dowdlelt/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/dowdlelt/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 58412772 into shape (64887,297)`

Passed godec.py the zcat image produced as an intermediate of MEICA, echo times and rank 1 (though changing rank does not change error). Notably, array size of 58412772 is 64887 * 297 * 3 (number of echoes), so it seems like it is expecting something slightly different. Providing a single image also fails.

**Comment by emdupre** [comment]
Hi @dowdlelt ! Thanks for reporting.

This is not yet "officially" supported in ME-ICA, though @prantikk may have another version of that code that he's able to share. Our priority right now is re-releasing ME-ICA (with reporting) in a BIDS App framework, before moving on to extensions such as GODEC.

That being said, if you'd like to open a pull request to add in GODEC now, I'd be happy to review it !

**Comment by prantikk** [comment]
Hey all, godec isn’t included directly but a similar feature, minimum image regression, is included. If you check recent Meica outputs, the motion related perturbations should be removed as done by godec, as seen in gray plots. In addition, the 0.1 version of godec is the one used by Power et al. It needs a bit of cleanup but should be usable.

**Comment by prantikk** [comment]
Also, godec runs on the final output images, like the hikts nifti,  not on the zcat files.

**Comment by dowdlelt** [comment]
Thanks @emdupre & @prantikk. This clears a few things up. I was able to get the 0.1 version of godec working to some extent but I'll look more closely at the T1c image - it may be just what I need.

Appreciate the quick updates - and all work on the code, its a fantastic resource! If I get some time I'll try and finish cleaning up the godec.py code, and learn how to do a pull request.

**Comment by dowdlelt** [comment]
To confirm the point that @prantikk made, here is an example figure comparing a grey plot between the tsoc, medn and T1c_medn data. Scaling identical.
##  Optimal Combination
![power_tsoc_plot](https://user-images.githubusercontent.com/15126366/36801396-00caa5fe-1c80-11e8-970f-edfedd0234a3.png)
##  Standard ME-ICA denoising
![power_medn_plot](https://user-images.githubusercontent.com/15126366/36801392-fed3f2f0-1c7f-11e8-9596-0ed709aa9587.png)
## ME-ICA denoising minumum image regression (T1c_medn) 
![power_t1c_medn_plot](https://user-images.githubusercontent.com/15126366/36801388-fbfee648-1c7f-11e8-9890-23c95d0c9361.png)
