### ISSUE TITLE
What version is this relative to the bit-bucket? +SMS-ME

### ISSUE THREAD

**Issue by KevinAquino** [ME-ICA/me-ica#6]
Hey all,

Just wondering how does this compare to the different Meica versions? Is it v3? Thanks!

Also I am trying this out on SMS fMRI are there any operational differences importing this into the code? Thanks!

**Comment by prantikk** [comment]
Hi
The current HEAD corresponds to v3.2.  There are no operational differences
in the application to SMS fMRI.
-Prantik

**Comment by KevinAquino** [comment]
Great thanks!
