### ISSUE TITLE
Spatial transformations 3Dwarp and 3Dresample and their influence on Meica. 

### ISSUE THREAD

**Issue by KevinAquino** [ME-ICA/me-ica#9]
Hi all,

This is partly a Meica.py question and mostly related to AFNI steps. 

I have been noticing a "hatching" in the temporal SNR maps in the Meica output -- medn (also present in the tsoc) from some recently acquired data and I have tracked it back to happen whenever there is a spatial interpolation namely 3Dwarp --deoblqiue and AFNI's 3Dresample. 

Below is an example of the TSNR map of the original time series of the 1st echo:

<img width="1038" alt="screen shot 2018-03-28 at 2 11 01 pm" src="https://user-images.githubusercontent.com/6628199/38069694-7169c426-3363-11e8-9662-886c09e2ff36.png">

And here is after 3DWarp -deoblique has been applied. 

<img width="1043" alt="screen shot 2018-03-28 at 2 11 08 pm" src="https://user-images.githubusercontent.com/6628199/38069696-72dd18da-3363-11e8-9463-421eaf5cfcc8.png">

these problems persist to the multecho denoised outputs. Is this someone else has been experiencing? Running Meica.py taking off the deoblique and any axialize operations, this hatching disappears (or at least minimised)

I'll also add that in the original data I can't see this hatching in the sagittal or coronal views of the same tSNR map.

Correct me if I'm wrong, It looks the steps include (without an anatomical input)
1. Spatial Interpolation to deoblique 
2. Axialize interpolation
3. Spatial Interpolation to isotropic voxels
4. Spatial Resampling back to the original data

Are these needed for a good estimate once using tedana.py? And which one of these are preferred?

Thanks! :)

**Comment by emdupre** [comment]
Thanks for reporting @KevinAquino !

I personally haven't seen this issue, so I am curious if it's at all related to the data itself. Is there any chance you could share the acquisition parameters ?

Either way, turning off axialize is actually a flag, so it's certainly not mandatory. To confirm, though-- Is it every interpolation that's causing the issue, or just deoblique ?

**Comment by prantikk** [comment]
This is likely not related to axialize, since axialize just rewrites the
data in a certain order.  However, 3dwarp might be at issue. Check the
interpolation options. You can try change to NN in the bash script produced
by meica.py

**Comment by KevinAquino** [comment]
Hey @emdupre and @prantikk Thank you for the speedy reply! sorry for my late reply was on Easter break and got caught up with students etc. 

Regarding the parameters: its SMS-ME, MB=4, 4 Echoes (13.8,34.43,55.06,75.69ms), and 3.25mm in-plane slice and 3.3 slice thickness and  IPAT=2 on a Siemens 3T Skyra using the Minnesota patch.  I had a deeper look into it and it seems the hatching is coming from a multi band artefact (the lines match up at the different multi band divisions)

Using the NN sorts out the issue which is great, I think the linear interpolation flag is affecting the data with non-isotropic voxels (I can replicate this with two different datasets). The last step with 3dresample also had this problem (when resampling back and moving the results back to the starting directory). 

Here are some tSNR maps of medn using NN interpolation:
<img width="1127" alt="screen shot 2018-04-18 at 2 42 35 pm" src="https://user-images.githubusercontent.com/6628199/38912219-68475dc2-4317-11e8-8aff-07d93e8091d5.png">
 
And finally using linear interpolation:
<img width="1138" alt="screen shot 2018-04-18 at 2 42 44 pm" src="https://user-images.githubusercontent.com/6628199/38912238-83a994cc-4317-11e8-8c77-2df01f4e01b5.png">

Linear interpolation is inflating the tSNR values and creating "hatching" artefacts in the data. The hatching might be specific to this dataset and (as well as another protocol we have). I have found turning off the oblique options entirely, and changing the last 3dresample seems to be a much more satisfying result. 

see an image below for the denoised images:
<img width="1118" alt="screen shot 2018-04-19 at 2 39 44 pm" src="https://user-images.githubusercontent.com/6628199/38971674-8a87c872-43df-11e8-9354-cc21efa108b2.png">

I've hacked away at this and added them to my Meica.py, I can add them in as proper arguments into Meica.py and send a pull request if you think it could be useful for anyone else?

**Comment by emdupre** [comment]
Thanks for following up, @KevinAquino ! Happy to hear that you were able to get this working for you.

Re adding options: you're more than welcome to submit a PR ! As a note on future development, we're actively working on [tedana](https://github.com/me-ica/tedana), which we hope to integrate into [FMRIPREP](https://github.com/poldracklab/fmriprep) so that we can capitalize on FMRIPREP's strengths in pre-processing and multi-echo's strengths in component analysis.

In the short term, though, users who are preprocessing multi-band, multi-echo data are likely to encounter similar issues, so I'd be happy to review code proposing an additional argument. Let me know how that sounds to you.

**Comment by KevinAquino** [comment]
Cool! I'll get something worked up a little less hacky to what I have now and send it through!

Thanks for your help!
